# Copyright 2022 (c) Microsoft Corporation.
# Licensed under the MIT license.
name: Azure Deployment Workflow
on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch

env:
  LOCATION: "eastus"  # Default value for location
  NAME: "mydeployment"  # Default value for name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Deployment
        run: |
          az deployment sub create --name ${{ env.NAME }}-deployment --location ${{ env.LOCATION }} --template-file ./infra/main.bicep --parameters basename=${{ env.NAME }} location=${{ env.LOCATION }}
