name: Azure Deployment Workflow
on:
  push:
    branches:
      - main 
env:
  LOCATION: "eastus" 
  NAME: "mydeployment1" 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Deployment
        run: |
          az deployment sub create --name ${{ env.NAME }}-deployment --location ${{ env.LOCATION }} --template-file ./infra/main.bicep --parameters basename=${{ env.NAME }} location=${{ env.LOCATION }}
