name: Azure Deployment Workflow
on:
  push:
    branches:
      - main 
env:
  LOCATION: "eastus" 
  NAME: "mydeployment1" 
  AZURE_RESOURCEGROUP_NAME: "test"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Deployment
        run: |
          az group create --name $AZURE_RESOURCEGROUP_NAME --location $LOCATION
          az deployment group create --name ${NAME} --location ${LOCATION} --template-file './infra/main.bicep' --parameters basename=${NAME} location=${LOCATION}
