name: Azure Deployment Workflow
on:
  push:
    branches:
      - main 
env:
  LOCATION: "eastus" 
  NAME: "mydeployment1" 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Deployment
        run: |
          az deployment sub create --name $NAME --deployment --location $LOCATION --template-file './infra/main.bicep' --parameters basename=$NAME location=$LOCATION


           az group create --name $AZURE_RESOURCEGROUP_NAME --location $LOCATION
           az deployment group create --resource-group Newresource --template-file './actions/bicep/strorage.bicep'
